# Generated by Django 3.0.5 on 2020-04-17 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='parentCommentID',
            new_name='parentComment',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='postID',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='likemodel',
            old_name='postID',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='userID',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(max_length=144, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(max_length=144, upload_to=myapp.models.profilePicturePath)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.ProfileModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likemodel',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.ProfileModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.ProfileModel'),
            preserve_default=False,
        ),
    ]
