# Generated by Django 3.0.5 on 2020-04-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200416_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='following',
            field=models.ManyToManyField(related_name='followedBy', to='myapp.ProfileModel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='parentComment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='childComment', to='myapp.CommentModel'),
        ),
    ]
