# Generated by Django 3.0.5 on 2020-04-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_profilemodel_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='email',
            field=models.EmailField(default='mark1@test.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
