# Generated by Django 3.0.5 on 2020-04-29 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profilemodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='parentComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childComment', to='myapp.CommentModel'),
        ),
    ]
