# Generated by Django 3.0.5 on 2020-05-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200428_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationType', models.IntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='myapp.ProfileModel')),
                ('entity', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myapp.PostModel')),
                ('notifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifier', to='myapp.ProfileModel')),
            ],
        ),
    ]
