# Generated by Django 3.0.5 on 2020-05-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='entity',
            field=models.IntegerField(),
        ),
    ]
